# Generated by Django 2.0 on 2017-12-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
            ],
            options={
                'verbose_name': 'Категория видео',
                'verbose_name_plural': 'Категории видео',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория видео',
                'verbose_name_plural': 'Категории видео',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='v_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VideoCategory', verbose_name='Выбрать категорию'),
        ),
    ]
