# Generated by Django 2.0 on 2017-12-29 16:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171229_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание видео'),
        ),
    ]
