# Generated by Django 2.0 on 2018-01-07 17:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180107_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
    ]
