# Generated by Django 2.0 on 2018-01-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0005_auto_20180107_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название настройки')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='sites.Site')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Меню сайта',
                'verbose_name_plural': 'Меню сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название пункта меню')),
                ('url', models.CharField(max_length=255, verbose_name='URL пункта меню')),
                ('weight', models.IntegerField(verbose_name='Вес пункта меню')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SiteMenu', verbose_name='Привязать к меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SiteMenuItem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='top_menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SiteMenu', verbose_name='Верхнее меню'),
        ),
        migrations.AlterUniqueTogether(
            name='sitemenuitem',
            unique_together={('menu', 'weight')},
        ),
    ]
