# Generated by Django 2.0 on 2018-01-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
    ]
