# Generated by Django 2.0 on 2018-01-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_page_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='is_main',
            new_name='is_main_first',
        ),
        migrations.AddField(
            model_name='page',
            name='is_main_second',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
    ]
