# Generated by Django 2.0 on 2018-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180113_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default='', upload_to='pages', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='is_main_first',
            field=models.BooleanField(default=False, verbose_name='Первый блок инфо на главной'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_main_second',
            field=models.BooleanField(default=False, verbose_name='Второй блок инфо на главной'),
        ),
    ]
