# Generated by Django 2.0 on 2018-01-13 19:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180113_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Краткое содержание'),
            preserve_default=False,
        ),
    ]
