# Generated by Django 2.0 on 2018-01-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180114_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default='', upload_to='reviews'),
            preserve_default=False,
        ),
    ]
