# Generated by Django 2.0 on 2018-01-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_review_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='text',
        ),
    ]
