# Generated by Django 2.0 on 2017-12-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='product_big_proportions',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='product_small_proportions',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
