# Generated by Django 2.0 on 2017-12-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20171206_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='product_big_proportions',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='product_small_proportions',
        ),
    ]
