# Generated by Django 2.0 on 2017-12-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20171211_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.PositiveIntegerField(unique=True, verbose_name='Тип меню')),
            ],
        ),
        migrations.CreateModel(
            name='SiteMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.SiteConfig')),
                ('menuType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.MenuType')),
            ],
        ),
        migrations.CreateModel(
            name='SiteMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.SiteMenu')),
            ],
        ),
    ]
