# Generated by Django 2.0 on 2017-12-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20171228_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Настройка сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterModelOptions(
            name='sitemenu',
            options={'verbose_name': 'Меню сайта', 'verbose_name_plural': 'Меню сайта'},
        ),
        migrations.AlterModelOptions(
            name='sitemenuitem',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AddField(
            model_name='sitemenuitem',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.SiteMenuItem', verbose_name='Родительский пункт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemenuitem',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес пункта меню'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название настройки'),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.SiteConfig', verbose_name='Связать с настройкой сайта'),
        ),
        migrations.AlterField(
            model_name='sitemenuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.SiteMenu', verbose_name='Привязать к меню'),
        ),
        migrations.AlterField(
            model_name='sitemenuitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название пункта меню'),
        ),
        migrations.AlterField(
            model_name='sitemenuitem',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL пункта меню'),
        ),
    ]
