# Generated by Django 2.0 on 2017-12-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20171228_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemenuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.SiteMenuItem', verbose_name='Родительский пункт'),
        ),
    ]
