# Generated by Django 2.0 on 2017-12-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('config', '0007_auto_20171228_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sitemenuitem',
            unique_together={('menu', 'weight')},
        ),
    ]
