# Generated by Django 2.0 on 2017-12-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20171228_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='top_menu',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.SiteMenu', verbose_name='Верхнее меню'),
            preserve_default=False,
        ),
    ]
