# Generated by Django 2.0 on 2017-12-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_remove_sitemenu_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='top_menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.SiteMenu', verbose_name='Верхнее меню'),
        ),
    ]
