# Generated by Django 2.0 on 2017-12-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='category',
            new_name='product',
        ),
    ]
