# Generated by Django 2.0 on 2017-12-05 23:39

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='cropping',
        ),
        migrations.AddField(
            model_name='productimage',
            name='cropping_255x170',
            field=image_cropping.fields.ImageRatioField('image', '255x170', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping 255x170'),
        ),
    ]
